apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAgICAgICAgICAgImF1dGgiOiAiYzNwdmJHOTBZWEpsZGpneU9tZG9jRjlYYmtKUk5HVmphVGRFZVdGRldscDFNMFJpVW1KU1VuWlFWSHA0YXpReWJ6UTFTa009IiAKICAgICAgICAgICAgICAgIH0KICAgICAgICB9Cn0K
type: kubernetes.io/dockerconfigjson
